### ISSUE TITLE
test `full_protocol_is_correct`  failed.

### ISSUE THREAD

**Issue by qxzhou1010** [menonsamir/spiral-rs#2]
When I run `cargo test full_protocol_is_correct` , the result is failed. Details are follows:
```rust
running 2 tests
test server::test::larger_full_protocol_is_correct ... FAILED
test server::test::full_protocol_is_correct ... FAILED

failures:

---- server::test::larger_full_protocol_is_correct stdout ----
target_idx: 15492
pp size: 1523744
thread 'server::test::larger_full_protocol_is_correct' panicked at src/client.rs:217:9:
assertion `left == right` failed
  left: 1687584
 right: 1523744
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- server::test::full_protocol_is_correct stdout ----
target_idx: 192
pp size: 1966112
num_query_cts: 1
thread 'server::test::full_protocol_is_correct' panicked at src/server.rs:545:39:
called `Option::unwrap()` on a `None` value


failures:
    server::test::full_protocol_is_correct
    server::test::larger_full_protocol_is_correct
```

Please note that my machine does not support AVX512, so I use the normal NTT version in ntt.rs. I am not sure whether this change will result in a failure.

In addition, I am using the old version of Spiral from https://github.com/blyssprivacy/sdk/blob/main/lib/spiral-rs/Cargo.toml, which runs well.

So what's the main difference between the newest version and the older version?

**Comment by menonsamir** [comment]
Added a note in the README - this is just a fork for use in YPIR. The complete, working spiral-rs implementation is [here](https://github.com/blyssprivacy/sdk/tree/main/lib).
